version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/build

hooks:
  BeforeInstall:
    - location: server_clear.sh
      timeout: 3000
      runas: packages/server
  AfterInstall:
    - location: initialize.sh
      timeout: 3000
      runas: packages/server
  ApplicationStart:
    - location: server_start.sh
      timeout: 3000
      runas: packages/server
  ApplicationStop:
    - location: server_stop.sh
      timeout: 3000
      runas: packages/server