version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Build Starting on `date`
      - cd packages/server
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
artifacts:
  files:
    - packages/server/build/libs/*.jar
    - packages/server/scripts/**
    - packages/server/appspec.yml
  discard-paths: yes