#spring:
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#  datasource:
#    url: jdbc:mysql://doffy-database.c9jzqmenvakc.ap-northeast-2.rds.amazonaws.com:13306/doffy?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: admin
#    password: ehvlvmfhwprxm
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId:
#            clientSecret:
#            scope:
#              - email
#              - profile
#  mail:
#    host: smtp.gmail.com
#    port: 465
#    username:
#    password:
#    properties:
#      mail.smtp.auth: true
#      mail.smtp.ssl.enable: true
#      mail.smtp.ssl.trust: smtp.gmail.com\
#security:
#  jwt:
#    token:
#      secret-key:
#      access-token-expire-minute: 60 #minute
#      refresh-token-expire-minute: 60 #minute
#username: admin
